/* FAÇA A GRAVAÇÃO DO LOG(EMPRESA.TXT) COM OS COMANDOS
EXECUTADOS EM SQL */
TEE C:/TEMP/EMPRESA.TXT;
SOURCE C:/TEMP/EMPRESA.SQL;

/* 1 - MOSTRE O NOME DO DEPARTAMENTO ONDE NENHUM EMPREGADO TRABALHA */

/* 2 - MOSTRE OS DADOS DO EMPREGADO QUE TEM O MAIOR SALÁRIO */
/* 3 - MOSTRE NOME E FUNCAO DE QUEM GANHA MENOS */
/* 4 - MOSTRE OS DADOS DOS EMPREGADOS QUE GANHAM MENOS QUE A MÉDIA SALARIAL */
/* 5 - QUEM GANHA MAIS QUE QUALQUER GERENTE */
/* 6 - MOSTRA MÉDIA SALARIAL POR DEPTO */
/* 7 - QUEM GANHA MAIS DO QUE A MÉDIA SALARIAL DE QQER DEPTO*/
/* 8 - MOSTRE OS DADOS DOS EMPREGADOS QUE TEM ALGUM TELEFONE */
/* 9 - MOSTRE OS DADOS DOS EMPREGADOS E SEUS RESPECTIVOS TELEFONES */
/* 10 - DÊ UM BONUS DE R$ 300,00 PARA OS EMPREGADOS DO RH */
